### ISSUE TITLE
Lowercase opcodes / registers

### ISSUE THREAD

**Issue by sebastianw** [jtauber/dcpu16py#11]
Hi,

the hello.asm/hello2.asm examples don't compile because the opcodes/registers are all lower case. Can this be fixed? I can't find anything in the spec regarding case.

**Comment by jtauber** [comment]
I'll update my assembler to handle lowercase. Given the code samples from Notch, it's presumably expected to work with both cases.

**Comment by jtauber** [comment]
Note asm_pyparsing supports it (and note even if asm.py did, it doesn't yet support `dat`

**Comment by jtauber** [comment]
fixed by 3ff64c76cc60ffbc26a008ddde188e6b3bf6c022 although `dat` still coming
