### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by andre-d** [jtauber/dcpu16py#13]
Various issues need to be fixed to get it running in python3, py2to3 might get it most of the way.  Although it really could work in both.

**Comment by jtauber** [comment]
Yeah, I've thought about attempting to make it run in both.

**Comment by andre-d** [comment]
I can do it, what is your min python2 target?  I can just import some stuff for __future for things like having a print function in python2 (for stderr printing), or if you want earlier support I can do some logic up to ensure that older version of python will still work too.

**Comment by andre-d** [comment]
The two three issues are 

A) The print functions need to be wrapped in print("hi") vs print "hi"

B) Printing to stderr requires print("hi", file=sys.stderr), so that would require __future (2.6 or greater) or a compat function

C) When the assembler writes to a file it needs to write bytes() and not char() (2.6 or greater)

So just let me know if your min python target and I will do it up, these are all fine changes if you want to target 2.6+.

**Comment by jtauber** [comment]
I'm fine targeting 2.7 and above so go for it!

**Comment by andre-d** [comment]
Pull reqd in #16
