### ISSUE TITLE
No license attached to project

### ISSUE THREAD

**Issue by cgt** [jtauber/dcpu16py#2]
Without a license, other people are not legally allowed to use this project. Please add a file called LICENSE or COPYING containing the full text of an OSI (Open Source Intiative) approved software license. If you do want to impose petty restrictions on people using your software, I would recommend that you use the [MIT license](http://opensource.org/licenses/MIT). The MIT license is short and easy to understand as it contains very little legalese. Of course it is up to you, but I strongly recommend that you _do not_ choose a license you do fully understand the implications of.

[OSI approved licenses](http://opensource.org/licenses/alphabetical)

**Comment by jtauber** [comment]
Yeah, I'll make it MIT. That's what I used for most of my projects.
