### ISSUE TITLE
eliminate Cell

### ISSUE THREAD

**Issue by jtauber** [jtauber/dcpu16py#22]
One of the things I like least about my approach is the need for the Cell class.

Some people have questioned why its needs at all rather than just passing around the unboxed value. Well, here's the problem with that: the 11 operations SET, ADD, SUB, MUL, DIV, MOD, SHL, SHR, AND, BOR, XOR need to take _references_ to registers and memory locations not just values. In other words, `SET X, Y` need to call the SET method with the _register_ X not the value of X (so it can set the value of the Y register to the X register).

One alternative I did consider is passing around a tuple of the form (`type`, `identifier`) where `type` = `REGISTER` | `MEMORY` | `LITERAL` and `identifier` is either the register name or memory location or literal value. The problem with that is you end up doing conditionals based on `type`. Any time you do _that_, it makes the OO programmer in me scream for polymorphism.

Even if you try to do something clever like "values over 0xFFFF are register names" (e.g. 0x10000 = A register) you still end up with conditionals I'd rather avoid. And you still need to distinguish literals from memory locations.

**Comment by jtauber** [comment]
hmm, it occurs to me there one highly important characteristic of the operations that take a, b (SET, ADD, SUB, MUL, DIV, MOD, SHL, SHR, AND, BOR, XOR):

Only the first argument need be a reference and, in fact, has to be.

So you don't actually need to distinguish literals from memory location references. If you pass 0x123 as first argument, it _must_ be a memory location and for the second argument, you can alway resolve a memory location _before_ you call the operation method.

Of course, this does mean that get_operand has to behave slightly differently depending on whether it's being called for the first arg or second. But this might be a promising approach.

**Comment by jtauber** [comment]
Going to explore on a `cell-less` branch.

**Comment by andre-d** [comment]
What I did with my early emulator was to separate out the instructions from the setting/getting of the value.

As pseudocode: 

```
  a_portion, b_portion, opcode = fetchInstruction()
  a = fetchValue(a_portion)
  b = fetchValue(b_portion)
  v = execInstruction(opcode, a, b)
  setValue(a_portion, v)
```

This way, the instructions deal only in raw values, and placing that value back into memory at a is dealt with in a different function.

**Comment by jtauber** [comment]
oh interesting. any downsides you can think of?

**Comment by andre-d** [comment]
Speed mostly, but that does not really matter in a 100khz emulator....

**Comment by jtauber** [comment]
especially one in Python :-)

although one of my main motivations for eliminating Cell is it kills PyPy's speed.

**Comment by andre-d** [comment]
I actually used the Arrays module for my memory, seemed to give pypy a speed boost.  You can stick all the values in as native 16bit unsigned values.  Less memory use and faster pypy likely.

**Comment by jtauber** [comment]
yeah, I might do that too

**Comment by andre-d** [comment]
You can see the code for my (very much not up to spec emulator) https://github.com/andre-d/pydcpu/blob/master/dcpucore.py  I am not updating it anymore mainly as it didn't make sense to have two python emulators being worked on sidebyside.

**Comment by jtauber** [comment]
I'm now strongly leaning towards memory[0x10000] = A, memory[0x10001] = B and so one; at least for my `cell-less` branch.

**Comment by andre-d** [comment]
How will you avoid code duplication within the handlers for that?  Will each instruction need to check that?

edit: ah, now I see

**Comment by jtauber** [comment]
Now see https://github.com/jtauber/dcpu16py/pull/23
