### ISSUE TITLE
Create 'Opcode' class

### ISSUE THREAD

**Issue by swarmer** [jtauber/dcpu16py#25]
I was thinking that it may be useful to create 'Opcode' (or something similar) class which:
- Pretty-prints itself (for disassembler)
- Parses bytecode producing list of its instances (again for disassembler)
- Provides interface to be used by asm_pyparsing for parsing
- Knows how to write itself wth all arguments into emulator memory (possibly removing a lot of complexity from emulator)

Though I'm not sure how exactly should it look  or if this is a good abstraction at all.

**Comment by jtauber** [comment]
It might be a nice approach in a purely OO language but it seems overengineered for Python
