### ISSUE TITLE
Is it actually working?

### ISSUE THREAD

**Issue by sebastianw** [jtauber/dcpu16py#31]
Hi,

is the compiler/emulator actually in a working state at the moment? I can compile stuff but running it always ends up as an endless loop which uses 100% CPU.

**Comment by swarmer** [comment]
Run it with -d: `dcpu16.py -d example.obj`
I'm not sure why James Tauber [decided to disable dump by default](https://github.com/jtauber/dcpu16py/commit/621734e1d9a3301000487a304b4780929c946d70) before we have working IO.

**Comment by jtauber** [comment]
@sebastianw the code you are running probably _is_ in an endless loop :-)

**Comment by jtauber** [comment]
@swarmer explicit is better than implicit? I'd rather people just use -d if they want it (although I should add that to the README)

**Comment by sebastianw** [comment]
But it should print out an "Hello world" (hello.asm/hello2.asm from your examples repo) but it does nothing like that...

**Comment by swarmer** [comment]
Video output is work in progress.

**Comment by sebastianw** [comment]
Oh there is no output at all right now? That would explain a lot...

**Comment by jtauber** [comment]
the `video` branch now runs `hello.asm` successfully. requires PyGame at the moment

**Comment by swarmer** [comment]
My video-qt now runs `hello.asm` too (on both Python 2 and 3).
~200 kHz with terminal open, ~430 without terminal on my box.

**Comment by jtauber** [comment]
@swarmer nice!

**Comment by sebastianw** [comment]
Looks great!
