### ISSUE TITLE
Automatic testing

### ISSUE THREAD

**Issue by pwaller** [jtauber/dcpu16py#50]
I propose to commit machine code for "known good" programs (into the examples), and to have a test script which assembles all of the example programs and does a hash-wise comparison of old and new. Preferably, the test program should be able to run either of the assemblers.

Anyone fancy having a go? 

I've not been thinking so much about the emulator, but one could do the same with the emulator, making the test that the final memory state is unchanged.

**Comment by jtauber** [comment]
I'd definitely like to see a test like this for the assemblers (and examples)
