### ISSUE TITLE
Assembling failing with KeyError: 'O'

### ISSUE THREAD

**Issue by shauncarpenter** [jtauber/dcpu16py#57]
I keep on getting a thrown error when attempting to assemble this: https://gist.github.com/2338772
The error is like so:

File "../dcpu16py/asm.py", line 146, in <module>
    b, y = handle(token_dict, "op2_")
File "../dcpu16py/asm.py", line 74, in handle
    a = IDENTIFIERS[token_dict[prefix + "register"].upper()]
KeyError: 'O'

Replacing all instances of O in my code with a normal Register like C makes it compile fine.  I've tried running it with both Python 3.2 and 2.7, receiving the exact same error.

**Comment by jtauber** [comment]
I'll get this added to examples too

**Comment by shauncarpenter** [comment]
Well, how about once it is actually working.
Sure, setting O to another register makes it assemble, but it also entirely breaks it...

Am I misunderstanding the DCPU spec? can I actually use the O register as I have in my gist above? or is it an issue with the assembler not recognizing the O register?

**Comment by swarmer** [comment]
Yes, you can use `O`. Also try `./asm_pyparsing.py` instead of `./asm.py`.

**Comment by shauncarpenter** [comment]
A Slightly more verbose error, but still fairly similar:

  File "../../dcpu16py/asm_pyparsing.py", line 224, in <module>
    main()
  File "../../dcpu16py/asm_pyparsing.py", line 215, in main
    program = codegen(fd.read())
  File "../../dcpu16py/asm_pyparsing.py", line 186, in codegen
    b, y = process_operand(s.second)
  File "../../dcpu16py/asm_pyparsing.py", line 127, in process_operand
    return IDENTIFIERS[b.register], None
KeyError: 'O'

**Comment by shauncarpenter** [comment]
Also, I forgot to update my repo, so the final error is actually on line 130.

**Comment by andre-d** [comment]
I will take a look into this, it may be that we missed .lower() or .upper() or something for the O operator...

**Comment by andre-d** [comment]
O is actually missing as an identifier, fixing

**Comment by andre-d** [comment]
#59 should fix this
