### ISSUE TITLE
Incorrect looping

### ISSUE THREAD

**Issue by shauncarpenter** [jtauber/dcpu16py#64]
While running the compiled version of this code:

```
SET A, 0x0fff
SET I, 1;
:loop
    ADD I, 1
    SHL A, 1
    IFN 1, O
        SET PC, loop
SHR A, I
```

I get very unexpected output.
Firstly, the debug mode doesn't allow me to step through the code (seperate issue).
but ignoring that, here is the output:     https://gist.github.com/2339908

Notice lines 81-83, the instruction is IFN 0x01, O.  But O is equal to that value
Then notice the second last instruction, lines 257-259; the if block is skipped even though the if condition is true (O != 1)

**Comment by shauncarpenter** [comment]
Ok, when the `IFN 1, O` is changed to `IFN O, 1` the code works perfectly; somehow having O as the second operand is causing the values to get all mangled and the conditional to give the wrong result.

**Comment by andre-d** [comment]
Perhaps our emulator has an issue with comparing O to 1 vs 1 to O.  I will look into this.

**Comment by andre-d** [comment]
Ah, yeah, those instructions (in our implementation) assume that A will be in the memory/register.    I will fix this.

**Comment by andre-d** [comment]
Should be fixed in #68.  Tested with https://gist.github.com/f1e10d49aff1962b7998

With the incorrect logic it would display TFF, now it displays TTT as all the comparisons are the same logically speaking.

**Comment by jtauber** [comment]
isn't the problem with SHL in line 77 of https://gist.github.com/2339908 ? The shift-left of A is taking it over 0xFFFF and it's not wrapping?

**Comment by jtauber** [comment]
the SHL bug is fixed in c005394

**Comment by jtauber** [comment]
Ahh, I see the other bug now (the one fixed by #68). It stems from the way I got rid of Cells (see the dicussion under #22). Basically I assume the first arg is not a literal. This is fine for most ops but not the IFx ones. Going to review #68 now.

**Comment by shauncarpenter** [comment]
Well, it's working perfectly now if O is first in the IFN.
Nicely done!  I'm really liking this implementation.

**Comment by jtauber** [comment]
Should now work with 1 first too

**Comment by shauncarpenter** [comment]
Indeed, everything is working.
