### ISSUE TITLE
Search plugins in project folder, not in current directory

### ISSUE THREAD

**Issue by swarmer** [jtauber/dcpu16py#65]
If you `cd` out of project directory, debugger and terminals mysteriously stop working because plugin loader doesn't find them.

It's probably a reason why debugger doesn't work in #64.

**Comment by andre-d** [comment]
Ah, yeah, that would happen.  Fixing

**Comment by andre-d** [comment]
Although likely not the problem with #64 as the debugger works, he just cant step

**Comment by andre-d** [comment]
Fixed in #67, please close once merged
