### ISSUE TITLE
pygame terminal does not work

### ISSUE THREAD

**Issue by sebastianw** [jtauber/dcpu16py#73]
The pygame terminal does not work, it raises a TypeError:

```
sebastian@gucky:~/work/dcpu16/dcpu16py (master)$ ./dcpu16.py --term pygame hello.obj 
Traceback (most recent call last):
  File "./dcpu16.py", line 288, in <module>
    p = p(args)
  File "/home/sebastian/work/dcpu16/dcpu16py/plugins/terminalplugin.py", line 71, in __init__
    self.term = terminal.Terminal(args)
TypeError: __init__() takes exactly 1 argument (2 given)
```

I can't figure out why because in the `pygame_terminal.py` the `__init__` function does take 2 arguments (self + args).

**Comment by andre-d** [comment]
You likely have a copy of pygame_terminal.pyc sitting in your dcpu16py directory, it is loading from that (an old copy) rather than the copy of pygame_terminal.py inside the termimals/ folder.  Delete any terminal pyc files you have sitting in the directory from before we had a terminals folder.

**Comment by sebastianw** [comment]
Of course, that was it.
